# Generated by Django 5.1.7 on 2025-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AITS_USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('registrar', 'Registrar'), ('admin', 'Administrator'), ('academic registrar', 'Academic Registrar')], default='student', max_length=100, verbose_name='User Role'),
        ),
    ]
